export default {
    "Listings": [
        {
            buyerID:  "Gloria" ,
            phone: 91234567,
            earnings:   0  ,
            expenditure: 10.70,
            orderAccepted: true,
            orderCompleted: false,
            orderID: 4,
            restaurantName: "McDonald's",
            orderItems: "mcchicken",
            orderDate: "24 May 2024",
            orderTime: "12:00pm",
            Latitude: 38.893551,
            longitude: -77.0567364 ,
        },
        {
            buyerID:  "Gloria" ,
            phone: 91234567,
            earnings:   1.50  ,
            expenditure: 0.00,
            orderAccepted: true,
            orderCompleted: true,
            orderID: 3,
            restaurantName: "Parklane",
            orderItems: "caifan",
            orderDate: "20 May 2024",
            orderTime: "1:00pm",
            Latitude: 38.8952431,
            longitude: -77.0365674 ,
        },
        {
            buyerID:  "Gloria" ,
            phone: 91234567,
            earnings:   0  ,
            expenditure: 8.00,
            orderAccepted: true,
            orderCompleted: true,
            orderID: 2,
            restaurantName: "Pasta Express",
            orderItems: "aglio olio",
            orderDate: "10 May 2024",
            orderTime: "12:00pm",
            Latitude: 38.895132,
            longitude: -77.03612314 ,
        },
        {   buyerID:  "Gloria" ,
            phone: 91234567,
            earnings:   0  ,
            expenditure: 18.70,
            orderAccepted: true,
            orderCompleted: true,
            orderID: 1,
            restaurantName: "Zhang-Liang",
            orderItems: "mala tang",
            orderDate: "08 May 2024",
            orderTime: "12:00pm",
            Latitude: 38.8951,
            longitude: -77.0364 ,
        }
    ]
}